### PR TITLE
Fixes #8. -full-apply and -apply now work for picket fence observations

### LINKED ISSUE #8: full-apply option fails on picket fence observations
Steps to reproduce:
* Download the raw visibilities from any picket fence observation from the MWA ASVO
* Request calibration solution (as per the [MWA wiki](https://wiki.mwatelescope.org/display/MP/Web+Services#WebServices-GetthecalibrationsolutionforaspecificcalibratorobservationID(experimental!))) 
* Run cotter with the -full-apply parameter
* Cotter will fail saying the solution file has the wrong number of channels 

I think the -fully-apply option is comparing the number of fine channels in the first contiguous subband (in the example below it's 1/2 the channels == 1536) with the number of channels in the calibration solution (the calibration solution .bin file will always just have all channels- in this case 3072).

So in a two subband picket fence like the one in the example, -full-apply needs to apply the calibration solutions from the .bin file for channels 0-1535 to the first contiguous band and then apply the calibration solutions from the .bin file for channels 1536-3071 to the second contiguous band.

Example:
```
$ cotter -absmem 64 -timeres 0.5 -freqres 10 -edgewidth 80 -initflag 4 -allowmissing -flagfiles 1245504832_%%.mwaf -full-apply cal/1245514896.bin -m 1245504832.metafits -o 1245504832.ms *.fits

Running Cotter MWA preprocessing pipeline, version 4.2 (2018-07-05).
Flagging is performed by AOFlagger 2.9.0 (2016-12-20).
Input filenames succesfully parsed: using 120 files covering 5 timeranges from 24 GPU boxes.
Using 64/125.6 GB of system memory.
Ignored keyword: ATTEN_DB
Ignored keyword: CHANSEL
Ignored keyword: INSTRUME
Ignored keyword: QUACKTIM
Ignored keyword: GOODTIME
Ignored keyword: COMMENT
Ignored keyword: COMMENT
Ignored keyword: COMMENT
Ignored keyword: COMMENT
Ignored keyword: COMMENT
Ignored keyword: COMMENT
Ignored keyword: COMMENT
Ignored keyword: COMMENT
Ignored keyword: HISTORY
Ignored keyword: HISTORY
Ignored keyword: HISTORY
Observation covers 72.32-169.59 MHz.
Output resolution: 0.5 s / 10 kHz (time avg: 1x, freq avg: 1x).
The first 8 samples (4 s), last 0 samples (0 s) and 8 edge channels will be flagged.
Using a-priori subband passband with 128 channels.
Using per-input subband gains. Average gains: 2.23853,2.00562,1.77026,1.57214,1.44202,1.38708,1.39087,1.40527,1.41077,1.38721,1.34753,1.30823,1.03528,1.0332,1.02271,1.01282,1.00232,0.997559,1,1.01001,1.01428,1.02368,1.03784,1.04456
Subband order: 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,23,22,21,20
Observation's bandwidth is non-contiguous.
 |=== BAND 1 / 2 ===|
Writing contiguous band 1 to 1245504832057-068.ms.

An unhandled exception occured while running Cotter:
The provided solution file has an incorrect number of channels. Oobservation has 1536 channels, and solution file has 3072 channels.
```

### PR DESCRIPTION
**Pull request by gsleap**
I believe with this branch/pull request this should fix issue #8 and allow a picket fence to have calibration solutions applied. I've done a fair amount of testing and it handles:
* one contiguous band (as expected)
* 2 or more contiguous bands 
* using -apply and -full-apply (i.e. after vs before averaging)

The main trick was, when in the ApplySolutionsWriter::WriteRow() function to have some idea of:
* How many fine channels are in the observation (this is needed to calculate channelRatio
* How many fine channels are in this contiguous band
* What is the start index of the first fine channel of this contiguous band
These pieces of info can then be used to find the correct channel indices in the cal solution and apply them to the data.

### CODE REVIEW

File: applysolutionswriter.cpp [hunk 1]
```diff
@@ -36,37 +38,47 @@ ApplySolutionsWriter::~ApplySolutionsWriter()
...
 	}
 }
 
-void ApplySolutionsWriter::WriteRow(double time, double timeCentroid, size_t antenna1, size_t antenna2, double u, double v, double w, double interval, const std::complex<float>* data, const bool* flags, const float* weights)
+void ApplySolutionsWriter::WriteRow(double time, double timeCentroid, size_t antenna1, size_t antenna2, double u, double v, double w, double interval, const std::complex<float> *data, const bool *flags, const float *weights)
 {
-	// Apply solution to averaged data
-	int channelRatio = _nChannels / _nSolutionChannels;
-	
+	// Apply solution to averaged data or where resolution of cal solution is higher than the obs you are applying it to
```
Comment (aroffringa) [inline applysolutionswriter.cpp]: Can you clarify this comment? Do you mean something like `Apply solution to averaged data, taking into account that the resolution of cal solution might be higher than the obs you are applying it to` ?

File: applysolutionswriter.cpp [hunk 2]
```diff
@@ -36,37 +38,47 @@ ApplySolutionsWriter::~ApplySolutionsWriter()
...
+	int channelRatio = _nSolutionChannels / _nTotalFineChannels;
```
Comment (aroffringa) [inline applysolutionswriter.cpp]: This looks incorrect to me, but I'm not sure... It used to be that there are at least as many channels in the data as that there are channels in the solutions, so _nTotalFineChannels >= _nSolutionChannels. In this case, channelRatio would always either round to 0 or to 1. This would then apply the wrong solution in the next lines of code...

File: applysolutionswriter.cpp [hunk 3]
```diff
@@ -36,37 +38,47 @@ ApplySolutionsWriter::~ApplySolutionsWriter()
...
+		// This code might be being called:
+		// 1. Before averaging 
+		// or 
+		// 2. After averaging
+		//
+		// Also, the data we are correcting maybe be in one contiguous 24 coarse channel band or several contiguous bands.
+		// The below line, uses _bandFineChanStart to offset the solution channel (ch) and channelRatio to address the various
+		// combinations of these scenarios.
+		//
+		size_t solChannel = (ch + _bandFineChanStart) * channelRatio;
```
Comment (aroffringa) [inline applysolutionswriter.cpp]: If I'm right above, then the fix should be to change this line to
```
size_t solChannel = (ch + _bandFineChanStart) / channelRatio;
```
and the line above to
```
channelRatio = _nTotalFineChannels / _nSolutionChannels;

**Review by aroffringa — COMMENTED** [review]
Hi @gsleap , thanks for these changes! They look fine for me but as I commented inline in the code it looks like it might apply the wrong solutions. Great that you've taken this up.

File: applysolutionswriter.cpp (hunk 1 above)
Comment (gsleap) [reply applysolutionswriter.cpp]: Hi Andre, yes, you got it- I'll update this comment to be more clear!

File: applysolutionswriter.cpp (hunk 2 above)
Comment (gsleap) [reply applysolutionswriter.cpp]: hmmm, I'm not sure now either! So, in my testing I was using examples where:

- Solution was produced from a 10 kHz, 20Khz, 40kHz calibrator obs, resulting in 3072,1536 or 768 channels in the solution file, but mostly the 10 kHz case as most of MWA calibrators since Phase 2 have 10 kHz fine channels.

- The observations had 3072,1536 or 768 channels if using -full-apply or 3072/N,1536/N or 768/N channels if using after averaging (-apply) where N is the averaging factor (2,4,...) e.g. averaging a 10 kHz fine channels to 80 kHz fine channels.

So this resulted in the vast majority of cases where I had more solution channels than observation/data channels and this required setting the ratio so we skip every N channels in the solution file (which I think is what you original code did too).

So this should result in channelRatio always being >=1. The case where the solution channels are less than the total fine channels is caught and prevented in the if statement check in `ApplySolutionsWriter::WriteBandInfo()`. 

Does this make sense? I could be wrong here- I'm still on a bit of a learning curve when it comes to calibration!

Comment (aroffringa) [reply applysolutionswriter.cpp]: Thanks Greg. I think the code never "skips" solution channels. For example, in `WriteBandInfo` it says:
```
	if(_nChannels < _nSolutionChannels || (_nChannels % _nSolutionChannels) != 0) {
		std::ostringstream s;
		s << "The provided solution file has an incorrect number of channels. Observation has " << _nChannels << " channels, and solution file has " << _nSolutionChannels << " channels.";
		throw std::runtime_error(s.str());
	}
```
So the number of channels in the solution file has to be at most the number of channels written, and therefore no solution channels are skipped. If you've tried to use a situation where nChan<nSolutions, you should have triggered that exception; didn't you get that exception? 

he code does allow the other way around: if there are fewer channels in the solution file than in the output, than a single solution channel is applied to multiple output channels. For that reason, the channelRatio was "output channels" / "solution channels", so always >= 1, and the solution channel was output channel / channelRatio, which would make sure e.g. with 100 output channels and 25 solution channels, that solution channel 0 is used for output channels 0-3, solution channel 1 for 4-7, etc. With your code, always channel 0 would be used, which I think is not correct.

Come to think of it, your code assumes the channels of all bands are in one solution file, but the original solution file that I defined was never used with an interrupted frequency axis. The calibrate tool will always calibrate a single band in picket fence observations, not the full band, so there should always be a solution file per band, and not one solution file with all bands as is assumed in your code. Of course it's possible to concatenate multiple bands into one solution file, but not sure that functionality exists already somewhere. Without something like that, I don't think it makes sense to apply solutions like this. I see two possible solutions you could pursue:
- Read a solution file per band in Cotter. It's a bit of a logistical hasle, but doable. 
- Make sure solution files can hold information for all bands (in picket fence observations). This is probably easier, but requires concatenating the results from multiple calibrate runs.

All in all, it's probably important that you try to test the following sequence: calibrate some picket fence obs -> apply those solutions to some picket fence obs with cotter -> image to see if things go correctly.

Comment (gsleap) [reply applysolutionswriter.cpp]: Hi Andre, thanks for that.

@marcinsokolowski has produced a calibration database for pretty much all calibrator observations and @andreww5au built web services to allow anyone to download these (see [MWA Web Services on the wiki](https://wiki.mwatelescope.org/display/MP/Web+Services)). @marcinsokolowski  provides a single .bin file in the cases where the calibrator is picket fence.  The MWA ASVO uses this webservice, along with cotter to apply cal solutions (when requested) and produce a calibrated measurement set (or sets if picket fence), so the use case of all calibrator channels being in the one .bin file regardless is the main use case. I believe if people want to use cotter themselves with their own cal solutions, then there is trivial code which can combine many .bin with different channels into one .bin file, so I think this is ok. So, yeah we are already implmenting your second bullet point so it's good we are on the same page!

Just with: "I think the code never "skips" solution channels. For example, in WriteBandInfo it says:", I think the code you showed is your original code, but in my pull request I had changed it to:
```
if (_nSolutionChannels < _nTotalFineChannels || (_nSolutionChannels % _nTotalFineChannels) != 0) {
	std::ostringstream s;
	s << "The provided solution file has an incorrect number of channels. Observation has " << _nTotalFineChannels << " channels, and solution file has " << _nSolutionChannels << " fine channels.";
	throw std::runtime_error(s.str());
}
```
So if the number of channels in the solution file is less than the number of channels in the data, we will throw an exception. So for example if I try to apply a solution which has 768 channels to an observation of 1536 channels then this exception gets thrown.

hmm! So I thought at the time it was correct to disallow the condition of solution channels < obs channels, but it wouldn't be too hard to add to my change. What do you think?

I do believe that the case of solution chans >= observation chans works with the code I've supplied (and for picket fence cases)- I've done several cycles of cotter (-full-apply and -apply) then wsclean but I'm only a novice at radio imaging, but I know enough to tell the difference between an calibrated image and a calibrated one, especially for a point-like source. 

So, when comparing to an un-calibrated image the results are very encouraging- 4 example images attached non-calibrated and calibrated for obsid 1242552568 (ch057-068 and ch121-132 respectively) of HydA. I can provide the fits versions if you're keen to take a look, as the attached jpgs don't really work for this but you get the idea! In this case though, I got the cal solution file from John Morgan who concatenated the output of calibrate into a single .bin file for me as there have been issues getting the cal solution via the web services for this obs as the MRO has been offline for a few days with power / cooling issues.

I'll do some more testing over the next few days anyway to be more sure it works as expected.

1242552568_057-068_calibrated:
1242552568_057-068_calibrated

1242552568_057-068_not_calibrated:
1242552568_057-068_not_calibrated

1242552568_121-132_calibrated:
1242552568_121-132_calibrated

1242552568_121-132_not_calibrated:
1242552568_121-132_not_calibrated

Comment (aroffringa) [reply applysolutionswriter.cpp]: Hi Greg,

You'll probably have to do some deeper imaging and differential comparison to notice the difference of applying the wrong channel, but I think things will only go wrong when the solution file has fewer solution than the data, and in that case you say you throw an exception, so then the solutions will never be incorrectly applied.

However, having fewer solution channels than in the data is a reasonably common use-case, as one can do this sequence:

- Run Cotter on a calibrator data and average in frequency (e.g. 4 times)
- Calibrate the averaged data, produce a solution file with Nchan/4 channels.
- Run Cotter on target data and apply the solutions

In this case, the solutions need to be "extrapolated", i.e., a single solution channel needs to be applied to multiple data channels. I don't know how common this is but I think it should be fairly simple to keep supporting this. The case you're now supporting is "run Cotter without averaging, calibrate, run Cotter with averaging and apply solutions afterwards". This seems to be a strange use-case to me, and would already be supported by Cotter by applying the full-res solutions before averaging.

Comment (gsleap) [reply applysolutionswriter.cpp]: Hi @aroffringa, I've updated my local copy of the code to support both scenarios (well 3 scenarios)-
solution channels > data channels (before or after averaging)
solution channels < data channels (before or after averaging)
solution channels == data channels (before or after averaging)

My use case was that Marcin's web service produces me a calibration solution, and then I run cotter and apply it before averaging (this is the MWA ASVO use case), so hopefully not so strange when explained this way?  :-)

I'm currently doing some tests by imaging these various scenarios and ensuring the solutions are applied correctly in all cases. Once I'm pretty sure of that I'll push my commit and you can take a look!

**Comment by gsleap** [comment]
Hi @aroffringa - I've push a new commit that takes care of the 3 cases. 

- Solutions file channels == data channels
- Solutions file channels > data channels
- Solutions file channels < data channels

I tested these 3 cases with both -apply and -full-apply and I get nice images of HydA. 

Let me know what you think. I'm happy with this going into master once you're ok with it.

Cheers

Greg

**Review by aroffringa — APPROVED** [review]
Thanks Greg! Looks great!
